inherit_from: .rubocop_todo.yml
require:
  - rubocop-graphql
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable

GraphQL/MaxComplexitySchema:
  Enabled: false

GraphQL/MaxDepthSchema:
  Enabled: false

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash', 'heredoc']

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10
