inherit_from: .rubocop_todo.yml
require:
  - rubocop-graphql
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash', 'heredoc']

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10
