name: "CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test-api:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.4
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: buggetme_test
          POSTGRES_USER: budgetme
          POSTGRES_PASSWORD: budgetme
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://budgetme:budgetme@localhost:5432/buggetme_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bundle exec rspec

  lint-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Security audit dependencies
        run: bundle exec bundler-audit --update
      - name: Security audit application code
        run: bundle exec brakeman -q -w2
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel

  lint-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: ./ui
        run: npm ci
      - name: Run ESLint
        working-directory: ./ui
        run: npm run lint
